id: P9AC43783
initial_creation_type: input
source_metadata:
  title: Empowerment Series
  language: en
  description: 'Various writings on the subject of empowerment or initiation (abhiṣeka;
    dbang bskur), including rites for conferment (dbang chog):'
  volume:
    1e9f22c870a945d3ad4b710853f9b810:
      title: A Prayer to Jowo Rinpoche Combined with Aspirations and a Means to Receive
        the Four Empowerments
      parent: Prayers
    c6bad213db304b42a9430a8e7a817c48:
      title: 'Shower of Indestructible Splendour: A Self-Initiation for the Guru Practice
        of the Vidyādhara Assembly, from the Heart-Essence of the Vast Expanse'
      parent: Rites
    b41fef7d17734e51a8e083edba7aaf88:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Rites
    de520225a51f48e1ba54c2e1abba3aff:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Rites
    497602c8d15a46c0b49d92e7bcb9daef:
      title: 'Illuminating the Meaning of Empowerment: A Self-Initiation for the Female
        Practice of the Ḍākinī'
      parent: Rites
    44e0facaca8b44758784323459cd253e:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Rites
created_at: '2022-03-01T03:39:26.959345'
last_modified_at: '2022-03-01T03:39:26.959351'
